apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-ipfs-stress
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: go-ipfs-stress
    spec:
      containers:
      - name: go-ipfs
        image: "ipfs/go-ipfs:v0.4.5-pre1"
        command: ["/usr/local/bin/start_ipfs"]
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
